/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

const Trees = ({ props, posx, posy, posz }) => {
  const { nodes, materials } = useGLTF('/assets/img/hero/models/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.palette}
          scale={10}
          position={[posx, posy, posz]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/img/hero/models/scene.glb')

export default Trees
