/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

const House = (props) => {
  const { nodes, materials } = useGLTF('/assets/img/hero/models/house.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[110, -21, 21]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.palette}
          scale={4}
          position={[-100, 750, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/img/hero/models/house.glb')

export default House
