/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF /*useAnimations */ } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials /*animations*/ } = useGLTF(
    '/assets/img/horseback.gltf'
  )
  //const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <group position={[0, 0, 0]}>
          <group rotation={[0.04, -0.03, 0.04]}>
            <group position={[0.04, -0.5, 0.76]} rotation={[0, 0.05, -0.03]}>
              <group position={[0, 11.5, 24]} rotation={[0.44, 0, 0]}>
                <group position={[0, 14, 0.5]} rotation={[-0.37, 0, 0]}>
                  <group position={[0, 1.5, 10.5]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes['H_Mouth-Local'].geometry}
                      material={materials['Mouth_Large_Quadruped-Material']}
                      position={[0, 6.5, 8]}
                    />
                  </group>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['H_Head-Local'].geometry}
                    material={materials['Head_Large_Quadruped-Material']}
                    position={[0, 12, 10.5]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['H_Neck-Local'].geometry}
                  material={materials['Neck_Large_Quadruped-Material']}
                  position={[0, 15.5, 6.5]}
                />
              </group>
              <group position={[-10, 1, 16]} rotation={[-0.59, -0.01, 0.01]}>
                <group position={[0, -10.5, 4]} rotation={[0, 0, 0]}>
                  <group position={[0, -8, 2]} rotation={[-0.26, 0, 0]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes['FL_Leg2-Local'].geometry}
                      material={materials['FL_Leg2-Material']}
                      position={[0, -8, 2]}
                    />
                  </group>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['FL_Leg-Local'].geometry}
                    material={materials['FL_Leg-Material']}
                    position={[0, -4.5, 2]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['FL_Thigh-Local'].geometry}
                  material={materials['FL_Thigh-Material']}
                  position={[0, -2.5, 0]}
                />
              </group>
              <group position={[10, 1, 16]} rotation={[-0.51, 0.01, -0.01]}>
                <group position={[0, -10.5, 4]}>
                  <group position={[0, -8, 2]} rotation={[1.61, 0, 0]}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes['FR_Leg2-Local'].geometry}
                      material={materials['FR_Leg2-Material']}
                      position={[0, -8, 2]}
                    />
                  </group>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['FR_Leg-Local'].geometry}
                    material={materials['FR_Leg-Material']}
                    position={[0, -4.5, 2]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['FR_Thigh-Local'].geometry}
                  material={materials['FR_Thigh-Material']}
                  position={[0, -2.5, 0]}
                />
              </group>
              <group position={[0, 16.25, 8.01]}>
                <group position={[0.13, 0, -0.29]} rotation={[-0.26, 0, 0]}>
                  <group position={[0, 2.5, 0]} rotation={[0.56, 0, 0]}>
                    <group position={[0, 4, 0]} rotation={[0.37, 0.51, -0.11]}>
                      <group
                        position={[0.01, 10.05, 0.09]}
                        rotation={[-0.54, -0.54, -0.15]}
                      >
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes['Head-Local'].geometry}
                          material={materials['Head_A-Material']}
                          position={[0, 9, 0.5]}
                        />
                      </group>
                      <group
                        position={[7.24, 8.78, 0.03]}
                        rotation={[-3.13, 0.86, -0.29]}
                      >
                        <group
                          position={[11, 0, -0.5]}
                          rotation={[-0.9, -1, -2.24]}
                        >
                          <group
                            position={[8, 0, 0]}
                            rotation={[-1.22, 0, -0.17]}
                          >
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes['Right_Hand-Local'].geometry}
                              material={materials['SwordHand-Material']}
                              position={[2, -13, -0.5]}
                            />
                          </group>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Right_Forearm-Local'].geometry}
                            material={materials['RightForeArm-Material']}
                            position={[4, 0.55, 0.45]}
                          />
                        </group>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes['Right_Arm-Local'].geometry}
                          material={materials['RightArm-Material']}
                          position={[4, 1.5, 0]}
                        />
                      </group>
                      <group
                        position={[-7.26, 8.95, 0.04]}
                        rotation={[0.17, 0.01, 1.4]}
                      >
                        <group
                          position={[-11, 0, -0.5]}
                          rotation={[2.45, 0.5, -1.87]}
                        >
                          <group
                            position={[-8, 0, 0]}
                            rotation={[-0.94, 0.42, -1.2]}
                          >
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes['Left_Hand-Local'].geometry}
                              material={materials['LeftHand-Material']}
                              position={[-5, 0, -0.5]}
                            />
                          </group>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes['Left_Forearm-Local'].geometry}
                            material={materials['LeftForeArm-Material']}
                            position={[-3, 0.56, 0.45]}
                          />
                        </group>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes['Left_Arm-Local'].geometry}
                          material={materials['LeftArm-Material']}
                          position={[-4, 1.5, 0]}
                        />
                      </group>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['Chest-Local'].geometry}
                        material={materials['ChestA-Material']}
                        position={[0, 7, 0]}
                      />
                    </group>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes['Belly-Local'].geometry}
                      material={materials['Belly-Material']}
                      position={[0, -2, 0]}
                    />
                  </group>
                  <group
                    position={[-4, -0.5, 0]}
                    rotation={[-1.12, -0.1, -0.56]}
                  >
                    <group
                      position={[-0.5, -12, -0.5]}
                      rotation={[2.23, 0.21, -0.2]}
                    >
                      <group
                        position={[0, -10, 0.5]}
                        rotation={[-0.62, 0.12, 0.34]}
                      >
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes['Left_Foot-Local'].geometry}
                          material={materials['Leftfoot-Material']}
                          position={[0, -0.5, 2]}
                        />
                      </group>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['Left_Leg-Local'].geometry}
                        material={materials['LeftLeg-Material']}
                        position={[0.5, -5, -0.5]}
                      />
                    </group>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes['Left_Thigh-Local'].geometry}
                      material={materials['LeftThigh-Material']}
                      position={[0.05, -6, -0.06]}
                    />
                  </group>
                  <group position={[4, -0.5, 0]} rotation={[-1.24, 0.1, 0.54]}>
                    <group
                      position={[0.5, -12, -0.5]}
                      rotation={[2.37, -0.17, 0.24]}
                    >
                      <group
                        position={[0, -10, 0.5]}
                        rotation={[-0.52, -0.29, -0.32]}
                      >
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes['Right_Foot-Local'].geometry}
                          material={materials['RightFoot-Material']}
                          position={[0, -0.5, 2]}
                        />
                      </group>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['Right_Leg-Local'].geometry}
                        material={materials['RightLeg-Material']}
                        position={[0.5, -5, -0.5]}
                      />
                    </group>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes['Right_Thigh-Local'].geometry}
                      material={materials['RightThigh-Material']}
                      position={[-0.05, -6, -0.05]}
                    />
                  </group>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['Hip-Local'].geometry}
                    material={materials['Hip-Material']}
                    position={[0, 0.5, 0]}
                  />
                </group>
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['H_Chest-Local'].geometry}
                material={materials['Chest_Large_Quadruped-Material']}
                position={[0, 3.5, 15]}
              />
            </group>
            <group position={[0, 8.5, -16]} rotation={[-0.25, -0.11, 0.06]}>
              <group position={[0, 3.5, -5]} rotation={[-1.13, -0.06, 0.02]}>
                <group position={[0, 0, -12]} rotation={[-0.13, 0, 0.01]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['Tail3-Local'].geometry}
                    material={materials['Tail3-Material']}
                    position={[0, -1.19, -5]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['Tail2-Local'].geometry}
                  material={materials['Tail2-Material']}
                  position={[0, -1, -7]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['Tail1-Local'].geometry}
                material={materials['Tail1-Material']}
                position={[0, 0, -3]}
              />
            </group>
            <group position={[-10, 1.5, -11]} rotation={[0.61, 0, 0]}>
              <group position={[0, -11, -2]} rotation={[-0.09, 0, 0]}>
                <group position={[0, -9, -6]} rotation={[0.17, 0, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['BL_Leg2-Local'].geometry}
                    material={materials['BL_Leg2-Material']}
                    position={[0, -7.5, 1]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['BL_Leg-Local'].geometry}
                  material={materials['BL_Leg-Material']}
                  position={[0, -5, -2]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['BL_Thigh-Local'].geometry}
                material={materials['BL_Thigh-Material']}
                position={[0, -3, 0]}
              />
            </group>
            <group position={[10, 1.5, -11]} rotation={[-0.21, -0.01, 0]}>
              <group position={[0, -11, -2]} rotation={[0.2, 0, 0]}>
                <group position={[0, -9, -6]} rotation={[-0.18, 0, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['BR_Leg2-Local'].geometry}
                    material={materials['BR_Leg2-Material']}
                    position={[0, -7.5, 1]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['BR_Leg-Local'].geometry}
                  material={materials['BR_Leg-Material']}
                  position={[0, -5, -2]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes['BR_Thigh-Local'].geometry}
                material={materials['BR_Thigh-Material']}
                position={[0, -3, 0]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['H_Hip-Local'].geometry}
              material={materials['Hip_Large_Quadruped-Material']}
              position={[0, -0.5, -8]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/img/horseback.gltf')
