/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

const Sign = (props) => {
  const { nodes, materials } = useGLTF('/assets/img/hero/models/sign.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node_#0'].geometry}
        material={materials['sign-Material']}
        scale={[-6, 6, 6]}
        position={[250, 100, -250]}
        rotation={[0, -150, 0]}
      />
    </group>
  )
}

useGLTF.preload('/assets/img/hero/models/sign.glb')

export default Sign
