/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

const SignTwo = (props) => {
  const { nodes, materials } = useGLTF('/assets/img/hero/models/imchris.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node_#0'].geometry}
        material={materials['imchris-Material']}
        scale={[-6, 6, 6]}
        position={[-250, 100, -250]}
        rotation={[0, 90, 0]}
      />
    </group>
  )
}

useGLTF.preload('/assets/img/hero/models/imchris.glb')

export default SignTwo
